import {useState} from 'react';
import {UploadCloud} from 'lucide-react';
import {useQueryClient} from '@tanstack/react-query';
import {api} from '../api/client';

export function DataImport({roomId}:{roomId?:number}){
  const [file,setFile]=useState<File>(); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [building,setBuilding]=useState(''); const [room,setRoom]=useState(''); const [occupants,setOccupants]=useState('1'); const client=useQueryClient();
  async function createRoom(){if(!building||!room)return;setBusy(true);try{await api('/rooms/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({building,room_number:room,occupant_count:Number(occupants)||1})});setMessage('Room created. Select it above to import readings.');await client.invalidateQueries({queryKey:['rooms']});}catch(error){setMessage(error instanceof Error?error.message:'Could not create room.');}finally{setBusy(false)}}
  async function upload(){if(!file||roomId===undefined)return;setBusy(true);setMessage('Importing and aggregating readings…');try{const body=new FormData();body.append('file',file);const result=await api<{inserted:number;format:string;first_timestamp:string;last_timestamp:string;skipped_bad_rows:number}>(`/readings/upload-csv?room_id=${roomId}`,{method:'POST',body});setMessage(`${result.inserted.toLocaleString()} hourly readings imported (${result.format}).`);await client.invalidateQueries();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false)}}
  return <div className="border border-line bg-surface p-5"><div className="flex items-start gap-3"><UploadCloud className="mt-0.5 text-primary" size={20}/><div className="min-w-0 flex-1"><h2 className="font-semibold">{roomId===undefined?'Set up your first meter':'Load meter data'}</h2>{roomId===undefined?<><p className="mt-1 text-sm text-muted">Create a room before importing household consumption.</p><div className="mt-4 flex flex-wrap gap-2"><input aria-label="Building" placeholder="Building" value={building} onChange={e=>setBuilding(e.target.value)} className="w-32 rounded border border-line bg-raised px-3 py-2 text-sm"/><input aria-label="Room number" placeholder="Room number" value={room} onChange={e=>setRoom(e.target.value)} className="w-32 rounded border border-line bg-raised px-3 py-2 text-sm"/><input aria-label="Occupants" type="number" min="1" placeholder="Occupants" value={occupants} onChange={e=>setOccupants(e.target.value)} className="w-28 rounded border border-line bg-raised px-3 py-2 text-sm"/><button disabled={!building||!room||busy} onClick={createRoom} className="rounded bg-primary px-4 py-2 text-sm font-semibold text-canvas disabled:opacity-40">Create room</button></div></>:<><p className="mt-1 text-sm text-muted">Upload the UCI household CSV or a file with <span className="mono">timestamp,reading_kwh</span> columns. UCI minute readings are converted to hourly kWh automatically.</p><div className="mt-4 flex flex-wrap items-center gap-3"><input aria-label="Choose consumption CSV" type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0])} className="max-w-full text-sm text-muted file:mr-3 file:rounded file:border-0 file:bg-raised file:px-3 file:py-2 file:text-ink"/><button disabled={!file||busy} onClick={upload} className="rounded bg-primary px-4 py-2 text-sm font-semibold text-canvas disabled:cursor-not-allowed disabled:opacity-40">{busy?'Importing…':'Import CSV'}</button></div></>}{message&&<p className="mt-3 text-sm text-flow">{message}</p>}</div></div></div>
}
