import {useState} from 'react';
import {Plus, X} from 'lucide-react';
import {useQueryClient} from '@tanstack/react-query';
import {api} from '../api/client';

export function RoomCreate(){
  const [open,setOpen]=useState(false); const [building,setBuilding]=useState(''); const [room,setRoom]=useState(''); const [occupants,setOccupants]=useState('1'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const client=useQueryClient();
  async function submit(e:React.FormEvent){e.preventDefault();if(!building.trim()||!room.trim())return;setBusy(true);setMessage('');try{await api('/rooms/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({building:building.trim(),room_number:room.trim(),occupant_count:Math.max(1,Number(occupants)||1)})});await client.invalidateQueries({queryKey:['rooms']});setMessage('Room created successfully.');setBuilding('');setRoom('');setOccupants('1');}catch(error){setMessage(error instanceof Error?error.message:'Could not create room.');}finally{setBusy(false)}}
  return <div className="relative"><button onClick={()=>setOpen(value=>!value)} className="inline-flex items-center gap-2 rounded border border-line bg-surface px-3 py-2 text-sm text-ink hover:border-primary"><Plus size={16}/>{open?'Close':'Add room'}</button>{open&&<form onSubmit={submit} className="absolute right-0 z-20 mt-2 w-72 border border-line bg-raised p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Add another room</h3><button type="button" aria-label="Close add room form" onClick={()=>setOpen(false)}><X size={16}/></button></div><div className="space-y-2"><input required placeholder="Building (e.g. A)" value={building} onChange={e=>setBuilding(e.target.value)} className="w-full rounded border border-line bg-surface px-3 py-2 text-sm"/><input required placeholder="Room number (e.g. 102)" value={room} onChange={e=>setRoom(e.target.value)} className="w-full rounded border border-line bg-surface px-3 py-2 text-sm"/><input required min="1" type="number" placeholder="Occupants" value={occupants} onChange={e=>setOccupants(e.target.value)} className="w-full rounded border border-line bg-surface px-3 py-2 text-sm"/><button disabled={busy} className="w-full rounded bg-primary px-3 py-2 text-sm font-semibold text-canvas disabled:opacity-50">{busy?'Creating…':'Create room'}</button></div>{message&&<p className="mt-3 text-xs text-flow">{message}</p>}</form>}</div>
}
